export const CONTENT = [
  'Esta aplicación es una plataforma para coleccionar cartas digitales de desarrolladores reales. Cada carta es una representación visual y simbólica de un desarrollador: su rol, sus herramientas favoritas y su personalidad.',
  'El objetivo no es solo coleccionar, sino inmortalizar a quienes escriben el futuro y fomentar la conexión entre personas del mundo del desarrollo.',
  'Cada carta es única. Solo el desarrollador que representa recibe su copia física original, y en la parte trasera contiene un código único de canje. Este código permite que otras personas puedan sumar esa carta a su colección, como quien intercambia figuritas, pero con un sentido más profundo.',
  'Cuando alguien te comparte su carta, podés ingresar el código en la app para desbloquearla y agregarla a tu colección. Cada código solo puede usarse una vez por usuario, así que si ya tenés una carta, no podrás repetirla.',
  'Esto promueve la interacción entre personas: necesitás que alguien te comparta su carta, que la encuentres en un evento, o que la descubras como un easter egg en algún blog, charla o proyecto.',
  'Desde tu perfil vas a poder ver:',
  '· Las cartas que tenés',
  '· Cuántas te faltan',
  '· Qué rol o tecnología representa cada una',
  '· El diseño ilustrado de cada carta y su información',
  'El verdadero valor de esta colección está en el encuentro. Cada carta es una excusa para conectar con alguien, conocer su historia, su forma de pensar, o simplemente agradecerle por compartir su experiencia.',
  'Esta colección busca:',
  'Reconocer a desarrolladores y desarrolladoras de todas las áreas, roles y trayectorias.',
  'Crear comunidad a través del juego, la curiosidad y el coleccionismo.',
  'Registrar una cultura que muchas veces queda invisible: la del trabajo diario, el aprendizaje constante y el compartir con otros.',
  'Cada carta es un homenaje. Cada colección, un mapa de conexiones.',
  'PREGUNTAS FRECUENTES:',
  '¿Puedo tener más de una copia de la misma carta?',
  'No. Cada carta solo puede canjearse una vez por usuario.',
  '¿Cómo consigo nuevas cartas?',
  'Conectando con personas. Participando en eventos. Explorando. Cada carta es un punto de contacto entre vos y alguien que forma parte de esta cultura.',
  '¿Puedo tener mi propia carta?',
  'Sí. Las cartas se crean desde una curaduría comunitaria. Podés postularte o ser propuesto por otros. Si sos seleccionado, te diseñamos tu carta oficial, con tu código para compartirla como quieras.'
]